"""data1

Revision ID: 64e05aaafb63
Revises: 
Create Date: 2024-06-01 17:34:23.021288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e05aaafb63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('create_id', sa.Integer(), nullable=True),
    sa.Column('writer_id', sa.Integer(), nullable=True),
    sa.Column('delete_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleter_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_id'), 'department', ['id'], unique=False)
    op.create_table('employee',
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('create_id', sa.Integer(), nullable=True),
    sa.Column('writer_id', sa.Integer(), nullable=True),
    sa.Column('delete_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleter_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_employee_id'), 'employee', ['id'], unique=False)
    op.create_index(op.f('ix_employee_last_name'), 'employee', ['last_name'], unique=False)
    op.create_index(op.f('ix_employee_middle_name'), 'employee', ['middle_name'], unique=False)
    op.create_index(op.f('ix_employee_name'), 'employee', ['name'], unique=False)
    op.create_table('organisation',
    sa.Column('phone_number', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('create_id', sa.Integer(), nullable=True),
    sa.Column('writer_id', sa.Integer(), nullable=True),
    sa.Column('delete_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleter_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisation_id'), 'organisation', ['id'], unique=False)
    op.create_index(op.f('ix_organisation_name'), 'organisation', ['name'], unique=False)
    op.create_table('position',
    sa.Column('name', sa.String(length=400), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('create_id', sa.Integer(), nullable=True),
    sa.Column('writer_id', sa.Integer(), nullable=True),
    sa.Column('delete_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleter_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_id'), 'position', ['id'], unique=False)
    op.create_table('task',
    sa.Column('name', sa.String(length=2000), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('dead_line_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('expired_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.Enum('DRAFT', 'WORKS', 'COMPLETED', name='taskstateenum'), server_default='DRAFT', nullable=False),
    sa.Column('started_by', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('create_id', sa.Integer(), nullable=True),
    sa.Column('writer_id', sa.Integer(), nullable=True),
    sa.Column('delete_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleter_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_dead_line_date'), 'task', ['dead_line_date'], unique=False)
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    op.create_table('task_and_assigner',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('complete_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('expired_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type_of_assigner', sa.Enum('ASSIGNER', 'OBSERVER', name='typeofassigner'), nullable=False),
    sa.Column('note', sa.String(length=3000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('write_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('create_id', sa.Integer(), nullable=True),
    sa.Column('writer_id', sa.Integer(), nullable=True),
    sa.Column('delete_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleter_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_and_assigner_id'), 'task_and_assigner', ['id'], unique=False)
    op.create_index(op.f('ix_task_and_assigner_type_of_assigner'), 'task_and_assigner', ['type_of_assigner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_and_assigner_type_of_assigner'), table_name='task_and_assigner')
    op.drop_index(op.f('ix_task_and_assigner_id'), table_name='task_and_assigner')
    op.drop_table('task_and_assigner')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_index(op.f('ix_task_dead_line_date'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_position_id'), table_name='position')
    op.drop_table('position')
    op.drop_index(op.f('ix_organisation_name'), table_name='organisation')
    op.drop_index(op.f('ix_organisation_id'), table_name='organisation')
    op.drop_table('organisation')
    op.drop_index(op.f('ix_employee_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_middle_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_last_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_department_id'), table_name='department')
    op.drop_table('department')
    # ### end Alembic commands ###
