"""data3

Revision ID: 959aad0658e3
Revises: 0ae8e3a62a49
Create Date: 2024-05-27 19:17:18.726361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959aad0658e3'
down_revision: Union[str, None] = '0ae8e3a62a49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('hashed_password', sa.String(length=1024), nullable=False))
    op.add_column('employee', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('employee', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('employee', sa.Column('is_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'is_verified')
    op.drop_column('employee', 'is_superuser')
    op.drop_column('employee', 'is_active')
    op.drop_column('employee', 'hashed_password')
    # ### end Alembic commands ###
